services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db_test
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST_TEST}
      POSTGRES_PORT: ${POSTGRES_PORT_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
  
  db_test:
    image: postgres:latest
    container_name: test-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/testing_starter.sql.sql:/docker-entrypoint-initdb.d/init.sql

  tester:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: tester
    depends_on:
      - db_test
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST_TEST}
      POSTGRES_PORT: ${POSTGRES_PORT_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
  
volumes:
  postgres_data:
