services:
  # Traefik API Gateway
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./traefik/acme.json:/acme.json
    command:
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --providers.file.watch=true
    networks:
      - elektrohelper_network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    expose:
      - "8080"
    depends_on:
      - db
      - mail
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_EMAIL: ${MAIL_EMAIL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.main-api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.main-api.service=main-api"
      - "traefik.http.services.main-api.loadbalancer.server.port=8080"
    networks:
      - elektrohelper_network

  forums_app:
    build:
      context: ./forums_backend
      dockerfile: Dockerfile
    restart: always
    expose:
      - "9090"
    depends_on:
      - app
      - neo4j
      - elasticsearch
    environment:
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forums-api.rule=Host(`localhost`) && PathPrefix(`/forums-api`)"
      - "traefik.http.routers.forums-api.service=forums-api"
      - "traefik.http.services.forums-api.loadbalancer.server.port=9090"
    networks:
      - elektrohelper_network

  payment_app:
    build:
      context: ./payment_backend
      dockerfile: Dockerfile
    restart: always
    expose:
      - "9091"
    depends_on:
      - app
      - mongo_db
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment-api.rule=Host(`localhost`) && PathPrefix(`/payment-api`)"
      - "traefik.http.routers.payment-api.service=payment-api"
      - "traefik.http.services.payment-api.loadbalancer.server.port=9091"
    networks:
      - elektrohelper_network

  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/starter.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
    attach: false
    networks:
      - elektrohelper_network

  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    attach: false
    networks:
      - elektrohelper_network

  neo4j:
    container_name: neo4j_db
    image: neo4j:latest
    restart: always
    expose:
      - "7474" # Web UI
      - "7687" # Bolt protocol
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    attach: false
    networks:
      - elektrohelper_network

  elasticsearch:
    container_name: elasticsearch_db
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=password
      - xpack.security.enabled=false
    expose:
      - "9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: always
    attach: false
    networks:
      - elektrohelper_network

  mail:
    image: mailhog/mailhog
    expose:
      - "${MAIL_PORT}" # SMTP
      - "8025" # Web UI
    attach: false
    networks:
      - elektrohelper_network

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevent overwriting node_modules
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_FORUM_URL: ${VITE_FORUM_URL}
      VITE_PAYMENT_URL: ${VITE_PAYMENT_URL}
      VITE_PAYPAL_CLIENT_ID: ${VITE_PAYPAL_CLIENT_ID}
    depends_on:
      - traefik
      - app
      - forums_app
      - payment_app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`) && !PathPrefix(`/api`) && !PathPrefix(`/forums-api`) && !PathPrefix(`/payment-api`)"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
      - "traefik.http.routers.frontend.priority=1"
    networks:
      - elektrohelper_network

  db_test:
    image: postgres:latest
    container_name: db_test
    profiles:
      - testing
    environment:
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./database/testing_starter.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
    networks:
      - elektrohelper_network

  tester:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: tester
    profiles:
      - testing
    depends_on:
      - db_test
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST_TEST}
      POSTGRES_PORT: ${POSTGRES_PORT_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    networks:
      - elektrohelper_network

  payment_tester:
    build:
      context: .
      dockerfile: ./payment_tests/Dockerfile
    profiles:
      - testing
    networks:
      - elektrohelper_network

networks:
  elektrohelper_network:
    driver: bridge

volumes:
  postgres_data:
  postgres_test_data:
  neo4j_data:
  neo4j_logs:
  elasticsearch_data:
  mongo_data: