name: CI - Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      db_test:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_test
        volumes:
          - postgres_data:/var/lib/postgresql/data
          - ./database/starter_test.sql:/docker-entrypoint-initdb.d/init.sql
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Ensure correct file permissions
        run: |
          chmod -R 755 ./database
          chmod 644 ./database/starter_test.sql

      - name: Build app image
        run: docker-compose -f docker-compose.yml build app

      - name: Build tester image
        run: docker-compose -f docker-compose.yml build tester

      - name: Run tests
        run: docker-compose -f docker-compose.yml up tester

      - name: Clean up
        run: |
          docker-compose down -v
          docker rmi elektrohelper-app elektrohelper-tester
