name: Docker Compose CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.19.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Build and start the app and db services
        run: |
          docker-compose -f docker-compose.yaml up --build -d app db
        continue-on-error: false

      - name: Run tests (using tester service)
        run: |
          docker-compose -f docker-compose.yaml up --build -d tester
        continue-on-error: false

      - name: Run tests script
        run: |
          docker-compose exec -T tester /bin/sh -c "/scripts/test.sh"
        continue-on-error: false

      - name: Run app (after tests)
        run: |
          docker-compose -f docker-compose.yaml up --build -d app db
        continue-on-error: false

      - name: Run app script
        run: |
          docker-compose exec -T app /bin/sh -c "/scripts/run.sh"
        continue-on-error: false

      - name: Clean up Docker containers
        run: |
          docker-compose down
