name: Docker Compose CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: elektrohelper

        POSTGRES_HOST_TEST: db_test
        POSTGRES_PORT_TEST: 5432
        POSTGRES_USER_TEST: postgres
        POSTGRES_PASSWORD_TEST: postgres
        POSTGRES_DB_TEST: elektrohelper

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.19.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Build tester image
        run: |
            docker-compose -f docker-compose.yaml up --build -d tester
            # Wait for tester container to complete
            sleep 15  # Give it some time to execute; adjust as needed
            tester_exit_code=$(docker inspect --format '{{.State.ExitCode}}' elektrohelper-tester-1)
            # Check if the exit code is not 0 (failure)
            if [ "$tester_exit_code" -ne 0 ]; then
              echo "Tester service failed with exit code $tester_exit_code"
              exit 1  # This will stop the pipeline
            fi
        continue-on-error: false

      - name: Build app image
        run: |
          docker-compose -f docker-compose.yaml up -d --build app
        continue-on-error: false

      - name: Clean up Docker containers
        run: |
          docker-compose down
