name: Docker Compose CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: elektrohelper

        POSTGRES_HOST_TEST: db_test
        POSTGRES_PORT_TEST: 5432
        POSTGRES_USER_TEST: postgres
        POSTGRES_PASSWORD_TEST: postgres
        POSTGRES_DB_TEST: elektrohelper

        MAIL_HOST: mail
        MAIL_PORT: 1025
        MAIL_EMAIL: no-reply@elektrohelper.rs

        SERVER_PORT: 5173
        SERVER_URL: http://localhost:5173

        API_URL: http://localhost:8080/api

        NEO4J_URI: bolt://neo4j:7687
        NEO4J_USER: neo4j
        NEO4J_PASSWORD: password
        ASPNETCORE_ENVIRONMENT: Development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.37.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Build and run tester and payment_tester images
        run: |
          # Start both services and build them
          docker-compose up --build tester payment_tester

          # Wait a bit to let containers finish
          sleep 15

          # Check exit code of tester container
          tester_exit_code=$(docker inspect --format '{{.State.ExitCode}}' elektrohelper-tester-1)
          if [ "$tester_exit_code" -ne 0 ]; then
            echo "Tester service failed with exit code $tester_exit_code"
            exit 1
          else
            echo "Tester service passed successfully"
          fi

          # Check exit code of payment_tester container
          payment_tester_exit_code=$(docker inspect --format '{{.State.ExitCode}}' elektrohelper-payment_tester-1)
          if [ "$payment_tester_exit_code" -ne 0 ]; then
            echo "Payment tester service failed with exit code $payment_tester_exit_code"
            exit 1
          else
            echo "Payment tester service passed successfully"
          fi
        continue-on-error: false

      - name: Build app image
        run: |
          docker-compose -f docker-compose.yaml up -d --build frontend-app
        continue-on-error: false

      - name: Clean up Docker containers
        run: |
          docker-compose down
